### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Cooke** [firebase/firebaseui-web-react#21]
Nice lib. Any way to localize the components? I'm using this library as an npm module.

**Comment by nicolasgarnier** [comment]
I think the underlying issue is that the localized versions of [firebaseui-web](https://github.com/firebase/firebaseui-web/) are not distributed via NPM (which is how we import and depend on the library here...).

@bojeil-google any chance the localized versions of firebaseui-web will be distributed in the NPM build/release at some point?

e.g. we'd do something like     `const firebaseui = require('firebaseui/FR_fr');`

**Comment by bojeil-google** [comment]
Hmm, we don't have any tangible plans at the moment. May come later down the road.

**Comment by bodrin** [comment]
https://github.com/firebase/firebaseui-web#building-firebaseui does not help? (https://github.com/firebase/firebaseui-web/issues/84)

**Comment by garyforsterio** [comment]
@nicolasgarnier as there aren't any plans for the files to be distributed via NPM would this be the only alternative currently?

1. Build the `firebaseui` module in required languages (as @bodrin mentioned)
2. Fork this repository
3. Add the localized files from 1
4. Change [this](https://github.com/firebase/firebaseui-web-react/blob/master/src/FirebaseAuth.jsx#L54) `require()` statement to import the localized variation.

I think I might just end up integrating the component into my own source code then dynamically loading the localized `firebaseui` using Webpack's [Dynamic Imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports). Any thoughts on this? I'll try to see if I can contribute anything back to this repo.

**Comment by mmiszy** [comment]
How about we delete this line https://github.com/firebase/firebaseui-web-react/blob/814ad759dde744d87905d2b9ccea8aba3b267553/src/FirebaseAuth.jsx#L54

And ask uses to load firebase-ui from CDN?

**Comment by davemecha** [comment]
I don't know how to import the localized firebaseui builds in my webapp. The documentation at https://github.com/firebase/firebaseui-web#localized-widget does not help.

I tried to include a German locale in my app and downloaded it from the CDN to my `lib` folder. When I now try to import the sideloaded localized version like this:

```
import * as fbui from 'firebaseui';
import * as fbuide from '../lib/firebase-ui-auth__de';

console.log(fbui, fbuide);
```

My output is 
![image](https://user-images.githubusercontent.com/137976/48980870-c98a1880-f0ce-11e8-8efb-a69346f979fc.png)

So `firebaseui.auth` is `undefined` and I don't know how to use it properly. If someone can help me out here, It might help others as well. (https://github.com/firebase/firebaseui-web/issues/84#issuecomment-328223506)

----

I would really appreciate firebaseui to be served with different locals in their npm distribution. There are wrappers for angular or React, that don't easy work with sideloaded packages as well.

**Comment by gustavopch** [comment]
I have a workaround.

I'm using `patch-package` (https://www.npmjs.com/package/patch-package) to create a local patch of the `firebaseui` lib with the translated strings in my project.

**Comment by tomoyuki28jp** [comment]
https://stackoverflow.com/a/49930985
FYI: This code works for me. (without using  firebaseui-web-react)

**Comment by natarajanrodrigues** [comment]
> I have a workaround.
> 
> I'm using `patch-package` (https://www.npmjs.com/package/patch-package) to create a local patch of the `firebaseui` lib with the translated strings in my project.

Can you explain better how did you get this?

**Comment by gustavopch** [comment]
> > I have a workaround.
> > I'm using `patch-package` (https://www.npmjs.com/package/patch-package) to create a local patch of the `firebaseui` lib with the translated strings in my project.
> 
> Can you explain better how did you get this?

I don't have the exact steps here because I stopped using this lib, but it goes somewhat along this:
1 - Setup `patch-package`: https://www.npmjs.com/package/patch-package#set-up
2 - Change the strings you want inside the firebaseui package installed in node_modules and save the changed files.
3 - Follow the instructions to make a patch: https://www.npmjs.com/package/patch-package#making-patches.
4 - It'll create a folder `patches` in the root of you project. Now, every time you reinstall your packages, it will apply the same changes you have performed in the step 2.

**Comment by ScreamZ** [comment]
@nicolasgarnier Maybe it would've been easier if we just could pass the translation file as an option on startup… ? Is it hard to do that way ?

**Comment by barbalex** [comment]
@jhuleatt concerning your proposal to open a new issue in firebaseui-web-react (https://github.com/firebase/firebaseui-web/issues/662#issuecomment-598463823): It seems to me that this issue is to the point.

Unfortunately there has been no great solution how to achieve localization yet. I tried:
- Using patch-package. Did not work for me (the translated text still appeared in English)
- Downloading https://www.gstatic.com/firebasejs/ui/4.4.0/firebase-ui-auth__de.js, installing it as local file in package.json and declaring it a (yarn) resolution. Only got errors when building the dev package in GatsbyJS

**Comment by barbalex** [comment]
I just realized that I can easily build my own ui and use firebase.auth() functions for the good stuff. So that is my solution.

**Comment by dszymczuk** [comment]
Hi @barbalex 
I found another solution. It's not ideal, but better than build my own ui.
I need to translate to polish so I pasted polish texts.
I'm using (S)CSS modules in my project (but it doesn't matter).

### I pass className to 
```javascript
<StyledFirebaseAuth className={styles.loginExternalWrapper} uiConfig={uiConfig} firebaseAuth={firebase.auth()}/>
```

### And apply these styles:
```css
$hideTextSize: 0;
$showTextSize: 14px;

.loginExternalWrapper {
  :global(.firebaseui-idp-facebook){
    :global(.firebaseui-idp-text-long) {
      font-size: $hideTextSize;
      &:after {
        font-size: $showTextSize;
        content: "Zaloguj się z Facebook";
      }
    }

    :global(.firebaseui-idp-text-short) {
      font-size: $hideTextSize;
      &:after {
        font-size: $showTextSize;
        content: "Facebook";
      }
    }
  }

  :global(.firebaseui-idp-google){
    :global(.firebaseui-idp-text-long) {
      font-size: $hideTextSize;
      &:after {
        font-size: $showTextSize;
        content: "Zaloguj się z Google";
      }
    }

    :global(.firebaseui-idp-text-short) {
      font-size: $hideTextSize;
      &:after {
        font-size: $showTextSize;
        content: "Google";
      }
    }
  }
}
```

### Result

<img width="241" alt="Zrzut ekranu 2020-03-22 o 11 38 19" src="https://user-images.githubusercontent.com/539352/77247455-a96e5900-6c31-11ea-9bc4-84ea880e1cf3.png">

### Support other languages
You have to pass different styles to `className` of `StyledFirebaseAuth`.
